export const HOOKS: string[] = [
  'Você ainda repete este erro clássico no primeiro minuto?',
  'O segredo que 87% dos criadores escondem do seu feed',
  'Três sinais de que seu conteúdo está repelindo seguidores agora',
  'Se eu tivesse ouvido isso antes, teria dobrado as vendas',
  'Ninguém te contou por que seus vídeos travam no segundo três',
  'Você faria isso com o seu próximo roteiro?',
  'Pare agora e confira este ajuste de 5 segundos',
  'O dado que mudou a forma como planejo vídeos virais',
  'Você está ignorando essa trend simples e poderosa?',
  'Como viralizar sem dançar nem gastar em anúncios',
  'Qual desses erros você cometeu na última publicação?',
  'O mito que está deixando suas métricas no zero',
  'Três micro hábitos que seguram o público até o final',
  'Seu público abandona no segundo quatro? Resolvido aqui',
  'O roteiro que fez meus leads pedirem mais conteúdo',
  'Você conhece o Código #7 que todo viral aplica?',
  'Duas frases que transformam curiosos em seguidores fiéis',
  'Esse hack entrega retenção mesmo em nichos “difíceis”',
  'Você está pronto para quebrar o algoritmo hoje?',
  'O passo que diferencia um vídeo assistível de um memorável',
  'Seus números caíram? Experimente esta abertura direta',
  'Prenda a atenção sem precisar de cortes frenéticos',
  'Você sabe qual emoção dispara comentários imediatos?',
  'Quem disse que vídeos técnicos não podem ser virais?',
  'O mapa simples para criar ganchos inesquecíveis',
  'Seu CTA está espantando sua audiência sem você perceber',
  'Você já aplicou o looping invisível no gancho?',
  'A curiosidade que transforma espectadores em clientes',
  'O truque mais rápido para conectar briefing e trend',
  'Pergunta sincera: você viu isso em algum outro lugar?',
  'Sua bio está cheia de curiosos, mas ninguém compra?',
  'Quem tem trinta segundos para mudar o jogo hoje?',
  'Um roteiro, três formatos: pronto para usar agora',
  'E se o seu próximo vídeo render três colabs?',
  'Descobri por que seu público sai no meio do vídeo',
  'O erro #1 ao usar trend sem contexto real',
  'Você está explicando ou realmente mostrando valor?',
  'Gancho forte em 9 palavras? Aqui está',
  'Seu vídeo precisa de mais tensão? Use isso',
  'Esse storytelling curto segura até quem não conhece você',
  'Você sabe encaixar prova social em 5 segundos?',
  'A combinação exata entre nicho e trend desta semana',
  'O roteiro que já nasce pronto para Reels e Shorts',
  'Quer triplicar salvamentos com uma frase?',
  'Você está pronto para virar autoridade hoje?',
  'A pergunta que faz qualquer especialista parar e ouvir',
  'O movimento visual que garante retenção no segundo sete',
  'Você consegue segurar 40 segundos de curiosidade?',
  'Quem disse que conteúdo educativo não viraliza?',
  'Como transformar briefing seco em história envolvente',
  'Está faltando emoção no seu vídeo? Olha isso',
  'Essa frase dispara comentários em menos de um minuto',
  'O erro invisível que corta seu alcance pela metade',
  'Se eu te contar isso, você promete aplicar hoje?',
  'Você quer que o algoritmo te recomende para desconhecidos?',
  'A trend do momento adaptada para o seu nicho',
  'Por que os vídeos curtos ainda precisam de CTA forte',
  'Seu vídeo tem começo poderoso e fim esquecível?',
  'O loop que faz o público esperar pela virada',
  'Três palavras que chamam atenção de verdade',
  'Você sabe como entregar valor antes do quinto segundo?',
  'Esse roteiro é antibloqueio de criatividade',
  'Você aproveita o poder dos detalhes visuais?',
  'Seu público pula porque você entrega tudo de cara',
  'Dê play nesse roteiro e veja os salvamentos subirem',
  'Quem quer dobrar retenção com um checklist simples?',
  'Você está falando com a pessoa certa ou com todo mundo?',
  'Esse framework viral cabe no seu briefing de hoje',
  'Seu CTA está pedindo like ou desejo real?',
  'Como usar perguntas abertas sem parecer genérico',
  'O roteiro que transforma objeções em curiosidade',
  'Seu próximo vídeo pode render leads prontos',
  'Você confia em dados ou em achismo? Veja isso',
  'O passo a passo para trend + autoridade = viral',
  'Quer que comentem sem pedir “comenta aí”?',
  'E se você pudesse repetir este gancho em qualquer nicho?',
  'A frase que faz seu avatar se sentir visto',
  'Está pronto para uma virada surpreendente?',
  'Você está criando tensão ou apenas falando rápido?',
  'Checklist de retenção para aplicar já',
  'Este é o único código que você ignora?',
  'Você quer parar de depender de sorte para viralizar?',
  'A diferença entre conteúdo assistido e conteúdo lembrado',
  'Seu vídeo termina pedindo like? Melhore para isso',
  'Trend quente: veja como encaixar sem forçar',
  'Quando foi a última vez que você testou um CTA novo?',
  'Sua audiência entenderá essa promessa em 3 segundos',
  'Pare de apagar vídeos, ajuste este detalhe',
  'Você quer que compartilhem seu conteúdo hoje?',
  'Aperte play e veja o que faltava no seu roteiro',
  'Descubra o código invisível por trás dos salvamentos',
  'Você está com medo de parecer vendedor demais?',
  'Quem é o seu avatar em uma frase? Use aqui',
  'Gancho forte sem clickbait: prova nesta frase',
  'Seu vídeo pode virar autoridade em 40 segundos',
  'Você mediu sua retenção na semana passada?',
  'O roteiro mais rápido para converter curiosos em clientes',
  'Você está preparado para entregar a virada perfeita?',
  'Essa técnica garante comentários sem pedir opinião',
  'Seu público precisa ouvir isso hoje mesmo',
  'Transforme dados frios em história quente agora',
  'Você quer parar de improvisar no meio da gravação?',
  'O algoritmo ama isso, mas quase ninguém aplica',
  'Esse CTA faz seguidores virarem compradores',
  'Três pistas que mostram se o vídeo vai segurar até o fim',
  'Você gostaria de viralizar ensinando algo complexo?',
  'O roteiro que combina autoridade, emoção e urgência'
];

export const TITLES: string[] = [
  'Checklist definitivo de retenção em 40 segundos',
  'Gancho triplo para vídeos curtos irresistíveis',
  'Trend adaptada ao nicho com CTA poderoso',
  'Como converter curiosos em leads em um único vídeo',
  'Framework de roteiro viral para especialistas tímidos',
  'Storytelling express para humanizar autoridade técnica',
  'Plano de vídeo educativo com final memorável',
  'Roteiro híbrido para Reels, TikTok e Shorts',
  'Virada inesperada que ativa compartilhamentos',
  'Sequência visual que prende até o CTA',
  'Guia rápido para vídeos com objetivo de alcance',
  'Blueprint para vídeos de conexão emocional',
  'Argumento perfeito para CTA de ação direta',
  'Como aplicar os 19 códigos sem perder naturalidade',
  'Roteiro pronto para lançamentos relâmpago',
  'Sistema de variação de ganchos em segundos',
  'Calendário de conteúdo com consistência viral',
  'Roteiro com prova social embutida',
  'Estrutura para trend aplicada ao nicho B2B',
  'Manual do vídeo irresistível para freelancers',
  'Roteiro educativo com virada surpreendente',
  'Scripts que geram salvamentos automáticos',
  'Guia de CTA triplo para engajar e converter',
  'Narrativa curta que cria confiança imediata',
  'Roteiro com tensão crescente até a virada',
  'Sequência que entrega valor em cada segundo',
  'Modelo de vídeo para anunciar sem parecer venda',
  'Video script para profissionais de saúde holística',
  'Roteiro que transforma objeção em oportunidade',
  'Mini documentário de 40 segundos',
  'Framework para especialistas em agronegócio digital',
  'Guia para lançamentos recorrentes com retenção',
  'Roteiro com CTA social e comercial alinhados',
  'Script prático para consultores independentes',
  'Modelo para professores que querem viralizar aulas',
  'Script para marcas locais ganharem alcance',
  'Plano narrativo para bastidores autênticos',
  'Roteiro curto para provas antes e depois',
  'Blueprint de roteiro com tensão, twist e CTA',
  'Guia para vídeos de conversão com autoridade',
  'Manual visual para mostrar produto sem exagero',
  'Script engajador para nichos técnicos complexos',
  'Roteiro para criadores que querem constância',
  'Plano rápido de vídeo com CTA múltiplo',
  'Roteiro multi-plataforma pronto para gravar',
  'Modelo de vídeo com storytelling de cliente',
  'Script de autoridade com convite à conversa',
  'Roteiro educativo com checklist visual',
  'Manual prático de viradas inesperadas',
  'Script conversacional para lançamento orgânico'
];

export const BENEFITS: string[] = [
  'Mais produtividade diária nas mudas sem perder qualidade',
  'Redução visível de pragas com manejo preventivo realista',
  'Economia de insumos graças a processos enxutos',
  'Clientes mais confiantes por enxergarem bastidores transparentes',
  'Equipe alinhada com rotinas claras e simples',
  'Autoridade reforçada ao traduzir dados em histórias',
  'Agenda cheia com leads que chegam já educados',
  'Comunidade engajada porque se sente incluída',
  'Produtos lembrados mesmo dias após o vídeo',
  'Processos replicáveis que cabem na rotina corrida',
  'Mais salvamentos porque o conteúdo vira checklist visual',
  'Compartilhamentos orgânicos por entregar insight imediato',
  'Tom profissional sem parecer distante do público',
  'Conversão maior graças a CTA direto e empático',
  'Mensagens de clientes agradecendo pela dica simples',
  'Seguidores novos descobrindo sua expertise rapidamente',
  'Time motivado vendo resultados concretos nos números',
  'Agenda organizada com roteiros prontos antecipadamente',
  'Conteúdo educativo com cara de entretenimento',
  'Mais comentários por provocar reflexão imediata',
  'Audiência fidelizada com promessas cumpridas no vídeo',
  'Percepção de valor elevada com dados apresentados visualmente',
  'Clientes tomando ação após ver benefício tangível',
  'Histórias que geram identificação genuína no avatar',
  'Briefings mais claros transformados em planos visuais',
  'Branding consistente em todos os formatos curtos',
  'Efeito “quero saber mais” ao final do CTA',
  'Credibilidade ampliada com provas reais mostradas',
  'Planejamento semanal mais leve com scripts organizados',
  'Maior taxa de retenção até a virada final',
  'Melhor alinhamento entre promessa e entrega do vídeo',
  'Sensação de proximidade sem perder profissionalismo',
  'Resultados medidos com métricas em ascensão',
  'Menos improviso e mais segurança na gravação',
  'Narrativas que destacam diferenciais únicos do nicho',
  'Conexão emocional construída em segundos',
  'Autoridade percebida ao explicar processo passo a passo',
  'Público curioso pedindo a parte dois',
  'Hashtags estratégicas com contexto claro',
  'Audiência voltando para rever anotações',
  'Sensação de urgência para aplicar a dica agora',
  'Time comercial recebendo leads preparados',
  'Comunidade compartilhando nos grupos privados',
  'Avaliações positivas destacando clareza e objetividade',
  'Clientes recorrentes renovando contratos com facilidade',
  'Conteúdo alimentando campanhas futuras com base sólida',
  'Menos tempo travado na tela em branco',
  'Briefing transformado em roteiro gravável rapidamente',
  'História do cliente se tornando prova social instantânea',
  'Tom de voz humano que reforça confiança',
  'Objeções desarmadas ao longo do desenvolvimento'
];

export const TWISTS: string[] = [
  'Revele que o maior ganho veio de um ajuste de um minuto',
  'Mostre a comparação antes e depois no mesmo take',
  'Entregue o resultado principal antes da explicação completa',
  'Troque a promessa por uma pergunta que expõe um erro comum',
  'Revele um bastidor imperfeito que gera identificação',
  'Mostre que o segredo é mais simples do que parece',
  'Inverta o conselho clássico e prove o contrário',
  'Conte uma micro-história onde a tentativa falhou primeiro',
  'Inclua dado concreto que surpreende pelo tamanho',
  'Mostre um contraexemplo que derruba a objeção padrão',
  'Apresente um resultado inesperado vindo de quem menos esperava',
  'Vire a câmera e mostre bastidores reais sem filtro',
  'Use um objeto inusitado para ilustrar o conceito',
  'Traga uma fala de cliente que contradiz o senso comum',
  'Quebre a expectativa entregando o benefício escondido',
  'Mostre planilha real ou número que ninguém compartilha',
  'Faça o público adivinhar e entregue a resposta oposta',
  'Mostre o erro acontecendo e como evitá-lo imediatamente',
  'Aponte que o truque “secreto” é apenas constância',
  'Use humor sutil para quebrar a tensão do tema',
  'Mostre que a solução não envolve comprar nada novo',
  'Traga comparação visual de dois caminhos possíveis',
  'Prove que menos etapas geram mais resultado',
  'Conte o bastidor da primeira vez que aplicou a dica',
  'Mostre uma mensagem real recebida depois de aplicar',
  'Revele que o algoritmo só reagiu quando você simplificou',
  'Mostre um print surpresa de métrica inesperada',
  'Entregue uma metáfora visual que ninguém esquece',
  'Mostre o efeito reverso caso a pessoa ignore a dica',
  'Inclua a dica bônus antes do CTA e amarre no final',
  'Explique por que o conselho popular está incompleto',
  'Faça a audiência completar uma frase e responda diferente',
  'Mostre um teste A/B e o resultado surpreendente',
  'Inverta a timeline e conte o final antes do início',
  'Inclua depoimento curto que confirma a transformação',
  'Mostre o que acontece se aplicar pela metade',
  'Use close dramático para revelar detalhe crucial',
  'Mostre que o benefício maior veio de uma pequena mudança',
  'Apresente uma metáfora sensorial para fixar a mensagem',
  'Demonstre ao vivo uma objeção sendo quebrada'
];

export const CTA_GROUPS = {
  engagement: [
    'Curte se isso fez sentido pra você',
    'Comenta "VIRAL" se quer a checklist completa',
    'Conta nos comentários qual parte você vai testar primeiro',
    'Marca alguém que precisa ouvir essa virada hoje',
    'Diz aqui se você já tentou algo parecido',
    'Comenta teu maior desafio com esse tema',
    'Escreve "QUERO" se quiser a parte dois',
    'Conta qual gancho funcionou melhor pra você',
    'Comenta a palavra-chave que resume essa dica',
    'Responde: você já aplica isso ou ainda não?',
    'Comenta o minuto que mais te surpreendeu',
    'Conta se quer que eu libere o roteiro em PDF',
    'Escreve "LISTA" se quiser os 19 códigos',
    'Diz aqui se quer mais bastidores como esse',
    'Conta qual trecho você vai adaptar ainda hoje',
    'Comenta "CAFÉ" se quiser o checklist do cultivo',
    'Escreve como você chamaria essa virada',
    'Conta qual parte do vídeo te segurou até o final',
    'Compartilha teu insight em uma frase',
    'Comenta se quer uma live destrinchando isso'
  ],
  follow: [
    'Segue pra aprender códigos virais toda semana',
    'Ativa o sininho pra não perder os próximos roteiros',
    'Me segue pra receber variações prontas no feed',
    'Salva meu perfil pra consultar quando faltar ideia',
    'Acompanha aqui pra garantir consistência sem burnout',
    'Segue e manda pra quem tá começando agora',
    'Fica por aqui que toda terça tem roteiro novo',
    'Segue se quiser virar referência no teu nicho',
    'Acompanha pra ver a parte dois em breve',
    'Segue pra não depender mais de improviso'
  ],
  save: [
    'Salva porque esse passo a passo vale ouro',
    'Clica em salvar pra revisar antes de gravar',
    'Guarda esse vídeo pra montar teu roteiro depois',
    'Salva e envia pro time alinhar o conteúdo',
    'Salva pra usar quando bater bloqueio criativo',
    'Marca como favorito e volta quando for gravar',
    'Salva pra provar pro cliente que dá pra viralizar',
    'Guarda essa dica pro planejamento de domingo',
    'Salva e marca a data no planner',
    'Deixa salvo pra comparar com teu próximo vídeo'
  ],
  action: [
    'Clica no link da bio e baixa o framework completo',
    'Me chama no direct com a palavra ROTEIRO pra consultoria',
    'Acessa o link fixado pra pegar o calendário editável',
    'Responde meus stories pra entrar no grupo fechado',
    'Arrasta pra cima... opa, só clicar no link da bio',
    'Vai no primeiro comentário e garante a vaga hoje',
    'Abre o link da bio e agenda um diagnóstico gratuito',
    'Preenche o formulário da bio pra receber o plano',
    'Clica no link da bio e salva tua vaga agora',
    'Entra no link da bio pra baixar o checklist completo',
    'Clica na bio e vê o kit de templates liberado',
    'Acessa o link da bio e garante o material bônus',
    'Visita a bio e pega o mapa de tendências atualizado',
    'Vai na bio e solicita o orçamento personalizado',
    'Entra no link da bio e se inscreve na aula gratuita',
    'Clica no link da bio e começa hoje mesmo',
    'Abre a bio e pega o guia avançado',
    'Solicita na bio o PDF com todos os códigos',
    'Vai no link da bio e baixa os exemplos editáveis',
    'Clica na bio e manda mensagem com a palavra CHAVE'
  ]
};

export const TIPS: string[] = [
  'Grave com a câmera na altura dos olhos e destaque as mãos em ação',
  'Mostre o bastidor real com luz ambiente antes de ligar o set',
  'Faça um corte rápido entre gancho e primeiro benefício',
  'Use legenda grande com palavras-chave do briefing',
  'Mostre o produto em close enquanto narra a virada',
  'Filme o antes e depois na mesma cena dividida',
  'Use transição simples apontando para o dado principal',
  'Grave em pé para transmitir energia e dinamismo',
  'Inclua B-roll de processo detalhado por cima da narração',
  'Mostre a planilha ou quadro enquanto fala do número',
  'Use iluminação lateral para destacar textura do produto',
  'Grave com microfone próximo para captar voz clara',
  'Inclua texto na tela com contagem regressiva da virada',
  'Use zoom suave quando revelar o twist',
  'Mostre o rosto reagindo ao erro comum',
  'Filmagem aérea com celular apoiado para mostrar o setup',
  'Inclua depoimento rápido com legenda flutuante',
  'Mostre a ferramenta sendo usada em close detalhado',
  'Grave a tela com demonstração passo a passo',
  'Use cortes jump-cut para manter ritmo acelerado',
  'Inclua gráfico simples desenhado à mão no quadro branco',
  'Filme outdoors para associar com liberdade do resultado',
  'Use iluminação natural na janela para humanizar',
  'Mostre checklist físico sendo marcado ao vivo',
  'Inclua movimento de câmera circular para criar tensão',
  'Filme com cenário real do local de trabalho',
  'Mostre o produto em uso por outra pessoa',
  'Inclua animação simples com setas apontando pontos-chave',
  'Grave o áudio separado e sobreponha para clareza',
  'Use câmera frontal e traseira alternadas rapidamente',
  'Mostre o cronômetro na tela para reforçar urgência',
  'Inclua sobreposição de emoji alinhada ao tom',
  'Use cartolina colorida para destacar item importante',
  'Grave em 60fps para aplicar slow motion na virada',
  'Mostre o ambiente antes da organização final',
  'Inclua ilustração simples desenhada ao vivo',
  'Use transição com estalo de dedo sincronizado',
  'Mostre os bastidores do equipamento improvisado',
  'Grave com amigo reagindo para reforçar prova social',
  'Inclua texto dinâmico no CTA final',
  'Mostre close nas expressões do rosto ao explicar',
  'Use corte para o céu ou teto criando respiro visual',
  'Grave com câmera apoiada em livros para ângulo criativo',
  'Inclua sons ambientes captados no local real',
  'Mostre passo a passo com números grandes na tela',
  'Use estabilização digital para evitar tremores',
  'Grave em ambiente externo com elementos do nicho',
  'Mostre a paleta de cores do produto nas mãos',
  'Use foco seletivo para destacar detalhe pequeno',
  'Inclua tela dividida mostrando duas abordagens',
  'Mostre reação espontânea ao ler feedback de cliente',
  'Grave enquanto anda para gerar movimento natural',
  'Inclua subtítulos com verbos de ação fortes',
  'Mostre storyboard desenhado rapidamente',
  'Use luz colorida suave para criar clima',
  'Filme com fundo neutro para destacar você',
  'Mostre o roteiro impresso ao lado do setup',
  'Inclua chamada visual no canto com CTA direto',
  'Mostre materiais utilizados alinhados em cima da mesa',
  'Use tripé improvisado com objetos do ambiente',
  'Inclua take de reação no final reforçando CTA'
];

export const DEFAULT_TRENDS: string[] = [
  'Desafio do áudio acelerado',
  'Trend do storytelling reverso',
  'Plano sequência com transição de mão',
  'Pergunta polêmica em 7 palavras',
  'Trend do antes e depois instantâneo',
  'Corte seco com zoom automático',
  'Trend da câmera baixa dinâmica',
  'Uso de legenda gigante minimalista',
  'Trend da música ambiente relaxante',
  'Dueto com especialista referência',
  'Trend da lista rápida em três passos',
  'Som viral com batida retrô',
  'Trend do diálogo com persona imaginária',
  'Trend do erro assumido na abertura',
  'Transição com palmas sincronizadas',
  'Trend do close no detalhe imperfeito',
  'Trend do texto piscando no ritmo',
  'Trend da pergunta “você sabia?”',
  'Trend da câmera girando 360 graus',
  'Trend do cenário trocado em um salto',
  'Trend do objeto caindo no gancho',
  'Trend do antes narrado pelo cliente',
  'Trend do plano vertical dividido',
  'Trend da contagem regressiva visível',
  'Trend do bastidor mostrando a gravação',
  'Trend do remix de vídeo antigo',
  'Trend da voz calma com tensão visual',
  'Trend do corte para texto manuscrito',
  'Trend do microfone em destaque',
  'Trend do filtro preto e branco com cor final',
  'Trend da câmera ultra aproximada',
  'Trend do apontar para legendas flutuantes',
  'Trend do silêncio dramático inicial',
  'Trend da troca de figurino rápida',
  'Trend do checklist aparecendo na tela',
  'Trend da coreografia mínima com storytelling',
  'Trend do mapa mental em segundos',
  'Trend do gráfico animado na tela',
  'Trend da sobreposição de prints reais',
  'Trend do reveal com mão tapando lente',
  'Trend da narração sobre escrita na lousa',
  'Trend da câmera tremida proposital',
  'Trend do diálogo com comentários da audiência',
  'Trend do improviso com legenda automática',
  'Trend da pergunta vs resposta imediata',
  'Trend do corte lateral mostrando bastidores',
  'Trend do storytelling com objeto simbólico',
  'Trend da iluminação natural na janela',
  'Trend do timelapse acelerado',
  'Trend da lista com emojis gigantes',
  'Trend do duo com especialista convidado'
];
